server:
  port: 8080
  netty:
    connection-timeout: 2s
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s